version: "2.1"

services:
  process-phone-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: process-phone-service:latest
    container_name: process-phone-service
    restart: always
    environment:
      PORT: 6100
      DB_TYPE: postgres
      DB_HOST: 103.211.206.96
      DB_PORT: 5432
      DB_USER_NAME: thobui14ig
      DB_PASSWORD: thobui14ig
      DB_DATABASE: crawl

      REDIS_HOST: 103.211.206.96
      REDIS_PORT: 2002
      REDIS_TYPE: single
    ports:
      - "6100:6100"
